# Generated by Django 4.1.6 on 2023-03-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='about_the_author',
            field=models.CharField(default='Биография автора', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='Authors'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='Books'),
        ),
    ]
