# Generated by Django 4.1.6 on 2023-03-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_author_about_the_author_author_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='about_the_author',
            field=models.TextField(max_length=1000),
        ),
    ]
