# Generated by Django 4.1.6 on 2023-04-12 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_author_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name'], 'permissions': (('can_add_author', 'Can add author'), ('can_change_author', 'Can change author'), ('can_delete_author', 'Can delete author'))},
        ),
    ]
